### ISSUE TITLE
how to send props to sketch function

### ISSUE THREAD

**Issue by cdaein** [jamesrweb/react-p5-wrapper#126]
Thank you for the great work. It's been very helpful to use the template.

I am trying to make `Sketch()` function more modular by separating p5 methods such as `setup()` and `draw()` into their own functions. I can pass `p`(p5) reference without a problem, but I am having an issue when passing `props`. Of course, if I follow the convention from the official example by defining `p.draw()` within `Sketch()`, props are recognized but as I have said above, I would like to make the p5 methods more modular.

If you have any suggestions, I'd appreciate it. Thank you!

```js
export default function Sketch(p) {
  let rotation = 0;
  let sz = 0;

  p.setup = setup(p);

  // props coming in from App component
  p.updateWithProps = (props) => {
    if (props.rotation) {
      rotation = props.rotation;
    }
    if (props.sz) {
      sz = props.sz;
    }
  };

  // group the props and send to draw() function
  const params = { rotation, sz };
  p.draw = draw(p, params);

  // the below method works fine.
  /*
  p.draw = () => {
    console.log({ rotation, sz });
    p.background(123);
    p.push();
    p.translate(p.width / 2, p.height / 2);
    p.rotate(rotation);
    p.rect(0, 0, sz, sz);
    p.pop();
  };
  */
}

function setup(p) {
  return () => {
    p.createCanvas(300, 200);
    p.rectMode(p.CENTER);
  };
}

function draw(p, params) {
  // issue: rotation, sz do not update inside draw()
  const { rotation, sz } = params;

  return () => {
    console.log({ rotation, sz });
    p.background(123);
    p.push();
    p.translate(p.width / 2, p.height / 2);
    p.rotate(rotation);
    p.rect(0, 0, sz, sz);
    p.pop();
  };
}
```

**Comment by jamesrweb** [comment]
Hi @cdaein, thanks for the interesting issue! I could reproduce what you are seeing and it is happening because of JS itself and how references to mutable primitives work (arrays, objects, etc.).

I created the following code for you to show an example of how to make things work as expected:

```js
import React, { useState, useEffect } from "react";
import { ReactP5Wrapper } from "react-p5-wrapper";

function setup(p5) {
  return () => {
    p5.createCanvas(300, 200);
    p5.rectMode(p5.CENTER);
  }
}

function draw(p5, props) {
  return () => {
    const { sz, rotation } = props;

    p5.background(123);
    p5.push();
    p5.translate(p5.width / 2, p5.height / 2);
    p5.rotate(rotation);
    p5.rect(0, 0, sz, sz);
    p5.pop();
  };
}

function sketch(p5) {
  let state = {
    rotation: 0,
    sz: 0
  }

  p5.updateWithProps = props => {
    state = Object.assign(state, props)
  };

  p5.setup = setup(p5);
  p5.draw = draw(p5, state);
}

export default function App() {
  const [rotation, setRotation] = useState(0);
  const [sz, setSZ] = useState(0);

  useEffect(() => {
    const interval = setInterval(
      () => {
        setRotation(rotation => rotation + 100)
        setSZ(sz => sz + 10)
      },
      100
    );

    return () => {
      clearInterval(interval);
    };
  }, []);

  return <ReactP5Wrapper sketch={sketch} rotation={rotation} sz={sz} />;
}
```

Let me know if this is what you expected and then I can close the issue. Thanks again for the question, I had fun figuring out what was going on.

**Comment by jamesrweb** [comment]
@yevdyko this could be another useful example for the documentation (if we can reduce the code a bit), WDYT?

**Comment by cdaein** [comment]
Yes, this works great! Thanks a lot for looking into this.

**Comment by jamesrweb** [comment]
> Yes, this works great! Thanks a lot for looking into this.

No problem, happy to have helped ✌🏻

**Comment by yevdyko** [comment]
> @yevdyko this could be another useful example for the documentation (if we can reduce the code a bit), WDYT?

@jamesrweb yes, that's a good idea! Will adapt it as an example.
