### ISSUE TITLE
p.textWrap(p.CHAR) not working

### ISSUE THREAD

**Issue by egroeg92** [jamesrweb/react-p5-wrapper#129]
## Actual Behavior

TypeError: p.textWrap is not a function

## Steps to Reproduce the Problem

use p.textWrap(p.CHAR);

## Specifications

I'm fairly sure this is to do with the version of p5 that is being imported - is there a way to check what p5 is being used and to use the most up to date one?

**Comment by jamesrweb** [comment]
We currently use the latest version, you can see this in the `package.json` of this repository.

Since the wrapper itself extends `P5`, anything `P5` exports in the "instance mode" is available to you without exception.

I've never personally used these methods, are you sure they aren't namespaced in the P5 instance mode?

**Comment by egroeg92** [comment]
thanks for responding!

Hmm this is very strange since the other text functions work.  I've tried the textWrap() function in a few different instances with no avail.

this the docs for the function.
https://p5js.org/reference/#/p5/textWrap

**Comment by egroeg92** [comment]
I'm using Next.js - code works when I comment out the textWrap function

```
import React, { Component } from 'react';
import dynamic from 'next/dynamic';


const ReactP5Wrapper = dynamic(import('react-p5-wrapper'), {
    ssr: false,
    loading: () => (
      <div className="sketch-holder">Loading...</div>
    ),
  });

function sketch(p){
    let mousePressed = false;
    let restart = false;
    let cnv;
    let myfont;

    let textbox;

    let quote = "hello how are you doing?"
    p.preload = () => {
      myfont = "Noto Serif Display";
    }
    
    p.setup = () => {
      p.createCanvas(710,400);
      textbox = p.createGraphics(400,250);
    }
  
    p.myCustomRedrawAccordingToNewPropsHandler  = props =>{


    }
    p.mousePressed = () =>{
        // setMousePressed(true);
        mousePressed=true;
    }
    p.mouseReleased = ()=>{
        // setMousePressed(false);
        mousePressed=false;

    }
    p.keyPressed = () =>{
      console.log(p.keyCode);
      if(p.keyCode === 83 ){
        p.saveCanvas(cnv,'chad.jpg');
      }
    }
    p.draw = () => {
      p.background('#f1f1f1');

      p.fill(0);
      p.noStroke();
      p.textFont(myfont);
      p.textSize(100);
      p.textAlign(p.LEFT,p.TOP);
      p.fill(0);
      p.push();
      p.scale(p.mouseX*0.01,p.mouseY*0.01);

      p.textWrap(p.ChAR);
      
      p.text(quote,0,0,p.mouseX,p.height);
      p.pop();      
      p.noFill();
      p.stroke('#ff0000');
      p.strokeWeight(5);
      var box_w =( p.textWidth(quote) * p.mouseX*.01)/3;

      // console.log(box_w);
      p.rect(0,0,box_w,p.height);

      var tbox_x=p.map(p.mouseX,0,p.width,0,textbox.width);
      var tbox_y=p.map(p.mouseY,0,p.height,0,textbox.height);
      textbox.background(51);
      textbox.fill(255);
      textbox.noStroke();
      textbox.push();
      textbox.scale(tbox_x,tbox_y);
      // textbox.translate(-tbox_x*.251,1);
      textbox.text(quote,0,0,p.mouseX,p.height);

      textbox.pop();
      textbox.noFill();
      textbox.stroke(255);

      // textbox.rect(0,0,box_w,tbox_y);
      
      p.image(textbox,150,75);
    }
}

export default function VariableFontExample() {

    return ( 
      <>

        <ReactP5Wrapper sketch={sketch} />
      </>
    )
  }

```

**Comment by jamesrweb** [comment]
You have a typo in your code, it should be `CHAR` but you wrote `ChAR` 😅!

I took the liberty of tidying your code up for you and correcting the typo, the following code works but you will need to adapt it to your needs as I removed some unused things and moved some stuff around for you!

```js
import React from 'react';
import { ReactP5Wrapper, P5Instance } from 'react-p5-wrapper';

/**
 * @param {P5Instance} p5
 */
function sketch(p5) {
  let cnv;
  let textbox;
  let mousePressed = false;
  let myfont = 'Noto Serif Display';
  let quote = 'hello how are you doing?';

  p5.setup = () => {
    p5.createCanvas(710, 400);
    textbox = p5.createGraphics(400, 250);
  };

  p5.draw = () => {
    p5.background('#f1f1f1');

    p5.fill(0);
    p5.noStroke();
    p5.textFont(myfont);
    p5.textSize(100);
    p5.textAlign(p5.LEFT, p5.TOP);
    p5.fill(0);
    p5.push();
    p5.scale(p5.mouseX * 0.01, p5.mouseY * 0.01);
    p5.textWrap(p5.CHAR);

    p5.text(quote, 0, 0, p5.mouseX, p5.height);
    p5.pop();
    p5.noFill();
    p5.stroke('#ff0000');
    p5.strokeWeight(5);

    var box_w = (p5.textWidth(quote) * p5.mouseX * 0.01) / 3;
    p5.rect(0, 0, box_w, p5.height);

    var tbox_x = p5.map(p5.mouseX, 0, p5.width, 0, textbox.width);
    var tbox_y = p5.map(p5.mouseY, 0, p5.height, 0, textbox.height);
    textbox.background(51);
    textbox.fill(255);
    textbox.noStroke();
    textbox.push();
    textbox.scale(tbox_x, tbox_y);
    textbox.translate(-tbox_x * 0.251, 1);
    textbox.text(quote, 0, 0, p5.mouseX, p5.height);

    textbox.pop();
    textbox.noFill();
    textbox.stroke(255);

    textbox.rect(0, 0, box_w, tbox_y);

    p5.image(textbox, 150, 75);
  };

  p5.keyPressed = () => {
    if (p5.keyCode !== 83) {
      return;
    }

    p5.saveCanvas(cnv, 'chad.jpg');
  };

  p5.mousePressed = () => (mousePressed = true);
  p5.mouseReleased = () => (mousePressed = false);
}

export default function App() {
  return <ReactP5Wrapper sketch={sketch} />;
}
```

> **Pro tip for using this library in regular JS:**
>
> If you want to get the benefits of Typescript types in regular Javascript code, you can do as I did in the above code and add a comment to say that the `p5` argument will be of type `P5Instance`. This will automatically be caught in code editors like vs code and you will get nice intellisense hints when interacting with the `p5` object given to you 👍🏻.

I hope this helped, let me know and then I will close the issue! 😄

**Comment by egroeg92** [comment]
This is very strange...

![image](https://user-images.githubusercontent.com/5962575/138358746-c05171dd-93c7-4f95-b64a-1fb3d123defa.png)

**Comment by jamesrweb** [comment]
> This is very strange...
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5962575/138358746-c05171dd-93c7-4f95-b64a-1fb3d123defa.png)
> 
> 

I'm not sure what's causing that, it seems like a nextjs issue to me because the code you sent works fine when the typo is corrected on my side in a standard create-react-app setup as demonstrated by the code I sent to you above. 🤷‍♂️

**Comment by egroeg92** [comment]
Yeah this is so weird! 

Must be a next.js thing but it seems so random since every other function works.

I appreciate your effort nonetheless - I'll try to work around it

**Comment by jamesrweb** [comment]
> Yeah this is so weird! 
> 
> 
> 
> Must be a next.js thing but it seems so random since every other function works.
> 
> 
> 
> I appreciate your effort nonetheless - I'll try to work around it

If you can't get it to work, reopen this issue and let me know what you tried and so on. Then I can try to take another look but for now I will close it, ok?

Good luck 🤞🏻

**Comment by egroeg92** [comment]
![image](https://user-images.githubusercontent.com/5962575/138363369-a264c557-a3c7-4df9-99e3-559861ada75c.png)

So I think the issue might be coming from using an older version of p5-wrapper.  But if I change the package.json to 3.0.2 and then run npm install then the program crashes... Any thoughts?

**Comment by jamesrweb** [comment]
Sounds like a next problem, updating the version shouldn't crash the app. I would recommend updating the dependency, using the code I sent as an example since that 100% works and restarting your app. If it's still breaking, it's 100% a next issue, if it isn't there must be another typo or something in your code I would assume because 2.4.0 is a stable version with no known issues and 3.0.0+ is designed for tree shakability and use in frameworks like next using modern react, etc.
