### ISSUE TITLE
Creates 2 Canvas elements 

### ISSUE THREAD

**Issue by nijatmursali** [jamesrweb/react-p5-wrapper#162]
Hello, I'm trying to test this library, but I'm facing some issues. I wanted to apply example code to display the element, but there it creates 2 canvas elements.

The code is:
```
import React from "react";
import { ReactP5Wrapper } from "react-p5-wrapper";

function sketch(p5) {
  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.draw = () => {
    p5.background(250);
    p5.normalMaterial();
    p5.push();
    p5.rotateZ(p5.frameCount * 0.01);
    p5.rotateX(p5.frameCount * 0.01);
    p5.rotateY(p5.frameCount * 0.01);
    p5.plane(100);
    p5.pop();
  };
}

export default function Test() {
  return <ReactP5Wrapper sketch={sketch} />;
}
```
![image](https://user-images.githubusercontent.com/16105077/167614309-4c1a38ca-182b-4bcd-8c77-1c393cff2147.png)

Can someone explain why this behavior happens?

I'm using  `"react-p5-wrapper": "^3.3.0"`.

**Comment by jamesrweb** [comment]
Using your exact code pasted here in [this REPL instance](https://replit.com/@jamesrweb/ScaryIrritatingBackend#src/App.jsx), I don't see the issue you see as shown in the video attached.

> For reference: The REPL is a simple create-react-app with your code pasted in, no changes.

https://user-images.githubusercontent.com/47126579/167615383-7547fff6-ad49-4b92-942f-e6f838a2e081.mov

**Comment by jamesrweb** [comment]
Perhaps you are rendering `Test` twice somehow or something but for sure the library is working as expected based on what I can see.

**Comment by nijatmursali** [comment]
It is really strange behavior as I don't have any other elements and I render that function just once.

**Comment by jamesrweb** [comment]
@nijatmursali can you share your full code and I can take a look?

**Comment by nijatmursali** [comment]
It's just the code I shared here and I'm just using it in index.js file:

```
root.render(
  <React.StrictMode>
    <Test/>
  </React.StrictMode>
);
```

Weird thing is that it works fine in incognito mode, but in normal mode of Chrome it shows 2 canvas elements.

**Comment by jamesrweb** [comment]
Try cache clearing, maybe you have 2 scripts in cache and browser loads both somehow.

**Comment by alexhalpin** [comment]
@nijatmursali I just spent 24 hours trying to fix the same issue, I fixed it by disabling the "honey" chrome addon. I hope this helps you.

**Comment by jamesrweb** [comment]
Haha wait what?! Honey creates a second canvas? what?

**Comment by jamesrweb** [comment]
I have never seen this happen before and I have many extensions so curious how that could resolve the issue and also if it is actually the problem @nijatmursali had 🤔.

**Comment by alexhalpin** [comment]
@jamesrweb 
I came to this solution when i read that @nijatmursali got rid of the second canvas by going incognito. That worked for me so I tried disabling all of my addons and that worked as well. I have a ton of addons as well but my first guess was honey and it turned out to be right haha. I tried enabling other addons and couldn't recreate the issue. 

honey enabled:
![image](https://user-images.githubusercontent.com/88046770/169348336-9a11c47f-95dd-4f17-9f53-a32a70d63e6c.png)

honey disabled:
![image](https://user-images.githubusercontent.com/88046770/169348454-71edce12-b0b0-40e0-97c6-7d04f5cb897a.png)

this happened with both react-p5-wrapper and react-p5 so i don't think its exclusive to this library.

**Comment by jamesrweb** [comment]
@zander0071 hilarious that chrome allows extensions to do this kind of thing but good work in finding that one. Could be good to document, perhaps I'll add something to the docs regarding this for future reference then!

**Comment by iosonosempreio** [comment]
Hello, I bumped into the same issue even with no extensions.
Looks ok while navigating, and the sketch is restarted at every visit. But If I refresh the page I end up having two canvases.
Using it in NextJS, the issue disappears after the website is exported.

Maybe related to the dynamic import?

```import styles from "./P5Effect.module.scss";
import dynamic from "next/dynamic";

const ReactP5Wrapper = dynamic(
	() => import("react-p5-wrapper").then((mod) => mod.ReactP5Wrapper),
	{ ssr: false }
);

function sketch(p5) {
	p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

	p5.draw = () => {
		p5.background(250);
		p5.normalMaterial();
		p5.push();
		p5.rotateZ(p5.frameCount * 0.01);
		p5.rotateX(p5.frameCount * 0.01);
		p5.rotateY(p5.frameCount * 0.01);
		p5.plane(100);
		p5.pop();
	};
}

export default function P5Effect() {
	return (
		<>
			<p>SKETCH</p>
			<ReactP5Wrapper sketch={sketch} />
		</>
	);
}
```

<img width="1215" alt="Screenshot 2022-05-20 at 12 56 38" src="https://user-images.githubusercontent.com/7115395/169513945-aa245443-c55c-4c37-b7c7-072100e0bbee.png">

EDIT
This is the generated canvas in HTML code

```
<div>
        <canvas id="defaultCanvas0" class="p5Canvas" style="width: 600px; height: 400px;" width="1200" height="800">
        <canvas id="defaultCanvas2" class="p5Canvas" style="width: 600px; height: 400px;" width="1200" height="800">
</div>
```

**Comment by jamesrweb** [comment]
> Hello, I bumped into the same issue even with no extensions.
> 
> Looks ok while navigating, and the sketch is restarted at every visit. But If I refresh the page I end up having two canvases.
> 
> Using it in NextJS, the issue disappears after the website is exported.
> 
> 
> 
> Maybe related to the dynamic import?
> 
> 
> 
> ```import styles from "./P5Effect.module.scss";
> 
> import dynamic from "next/dynamic";
> 
> 
> 
> const ReactP5Wrapper = dynamic(
> 
> 	() => import("react-p5-wrapper").then((mod) => mod.ReactP5Wrapper),
> 
> 	{ ssr: false }
> 
> );
> 
> 
> 
> function sketch(p5) {
> 
> 	p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);
> 
> 
> 
> 	p5.draw = () => {
> 
> 		p5.background(250);
> 
> 		p5.normalMaterial();
> 
> 		p5.push();
> 
> 		p5.rotateZ(p5.frameCount * 0.01);
> 
> 		p5.rotateX(p5.frameCount * 0.01);
> 
> 		p5.rotateY(p5.frameCount * 0.01);
> 
> 		p5.plane(100);
> 
> 		p5.pop();
> 
> 	};
> 
> }
> 
> 
> 
> export default function P5Effect() {
> 
> 	return (
> 
> 		<>
> 
> 			<p>SKETCH</p>
> 
> 			<ReactP5Wrapper sketch={sketch} />
> 
> 		</>
> 
> 	);
> 
> }
> 
> ```
> 
> 
> 
> <img width="1215" alt="Screenshot 2022-05-20 at 12 56 38" src="https://user-images.githubusercontent.com/7115395/169513945-aa245443-c55c-4c37-b7c7-072100e0bbee.png">
> 
> 
> 
> EDIT
> 
> This is the generated canvas in HTML code
> 
> 
> 
> ```
> 
> <div>
> 
>         <canvas id="defaultCanvas0" class="p5Canvas" style="width: 600px; height: 400px;" width="1200" height="800">
> 
>         <canvas id="defaultCanvas2" class="p5Canvas" style="width: 600px; height: 400px;" width="1200" height="800">
> 
> </div>
> 
> ```

I cannot reproduce this example either 🧐.

Furthermore theres a 0th and a 2nd but no 1st canvas and that tells me there's a render issue creeping in somewhere either via next or by configuration or something.

Not sure how this is suddenly cropping up for people but I really can't see anything that would be or could be causing this in the code base or in my replications of the examples shared.

**Comment by subodhpareek18** [comment]
![image](https://user-images.githubusercontent.com/12589797/177033957-e4e7081f-a271-4d68-b510-0254b302647c.png)

Facing the same issue while using vite.

```jsx
import { ReactP5Wrapper } from "react-p5-wrapper";

function sketch(p5) {
  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.draw = () => {
    p5.background(250);
    p5.normalMaterial();
    p5.push();
    p5.rotateZ(p5.frameCount * 0.01);
    p5.rotateX(p5.frameCount * 0.01);
    p5.rotateY(p5.frameCount * 0.01);
    p5.plane(100);
    p5.pop();
  };
}

function App() {

  return (
    <div className="App">
      <ReactP5Wrapper sketch={sketch} />;
    </div>
  )
}

export default App
```

 I randomly decided to give the wrapper component a key and that fixed it for me for some reason.

```jsx
function App() {

  return (
    <div className="App">
      <ReactP5Wrapper key={1} sketch={sketch} />;
    </div>
  )
}
```

**Comment by subodhpareek18** [comment]
Spoke too soon, still a problem as soon as I moved forward, would request you to repoen this issue

**Comment by subodhpareek18** [comment]
Had the same issue, solved by disabling Google Dictionary chrome extension

**Comment by xanderjl** [comment]
I know I'm late to the party, but this is occurring because react is in strict mode. It's re-rendering your code in the dev environment. [https://reactjs.org/docs/strict-mode.html](https://reactjs.org/docs/strict-mode.html) 

In your `next.config.js`:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
}

module.exports = nextConfig
```

**Comment by melaniehuang** [comment]
Yep same solution for me outside of Next.js.

I removed 
`<React.StrictMode>`
from my default create-react-app index.js file and the canvas no longer renders twice.

**Comment by vincerubinetti** [comment]
I don't think this should've been closed.

As annoying as the strict mode double-renders are, they're there for a reason: to catch problems with your useEffect cleanups. I'd wager that at present, most teams would find it unacceptable to disable strict mode for their app, or even on a specific component (if that's even possible?)

With React 19, p5 v2, and v5 of this library, I'm still seeing this canvas duplicating behavior. When reaching for a React wrapper component for some imperative library, I think most devs would expect the mounting and cleanup to be handled by the wrapper.
