### ISSUE TITLE
myCustomRedrawAccordingToNewPropsHandler not working

### ISSUE THREAD

**Issue by janie-lee-developer** [jamesrweb/react-p5-wrapper#163]
## Expected Behavior
myCustomRedrawAccordingToNewPropsHandler to work and console.log(props.passedProp), trying test passing props is working by just logging it.

## Actual Behavior
myCustomRedrawAccordingToNewPropsHandler not working at all, I added console.log(entered to function!), and this is not even logging in. The function isn't even running.
FYI- Sketch and set up is running fine!!!

## Steps to Reproduce the Problem

1. import { ReactP5Wrapper } from "react-p5-wrapper";
2. <ReactP5Wrapper sketch={sketch} rotation={rotation} />
3. inside the sketch function, I have const sketch = (p5) => {
p5.myCustomRedrawAccordingToNewPropsHandler = function (props) {
    if (props.rotation) {
      console.log("rotations", props.rotation);
    }
  };
}

## Specifications

Package Version: 3.3.0

I see many examples importing it as` import P5Wrapper from 'react-p5-wrapper';` and then `<P5Wrapper sketch={sketch} rotation={rotation}/>`
but when I do this, webpack fails to import react-p5-wrapper and it fails to build the app.. Pls help.

<img width="980" alt="0" src="https://user-images.githubusercontent.com/58411107/169456284-9e7e9a5d-818d-4289-847c-622660b6141c.png">

<img width="1165" alt="1" src="https://user-images.githubusercontent.com/58411107/169456087-34c6c0e5-2fc7-4f28-8a83-45e6e26a2086.png">

<img width="1334" alt="2" src="https://user-images.githubusercontent.com/58411107/169456108-49c45cf8-db48-4db3-b07b-cbf5f744331f.png">

<img width="1033" alt="3" src="https://user-images.githubusercontent.com/58411107/169456121-ec6861d4-77bb-4a6b-b324-203d67f093f6.png">

<img width="1156" alt="4" src="https://user-images.githubusercontent.com/58411107/169456154-991d9147-5de8-4ce8-8566-baa51021860d.png">

**Comment by jamesrweb** [comment]
Since version 3 we no longer support that method and instead use `updateWithProps`.

Here is the example taken from the documentation:

```tsx
import { ReactP5Wrapper } from "react-p5-wrapper";

function sketch(p5) {
  let rotation = 0;

  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.updateWithProps = props => {
    if (props.rotation) {
      rotation = (props.rotation * Math.PI) / 180;
    }
  };

  p5.draw = () => {
    p5.background(100);
    p5.normalMaterial();
    p5.noStroke();
    p5.push();
    p5.rotateY(rotation);
    p5.box(100);
    p5.pop();
  };
}
```

For a deeper dive into how prop reactivity works please read the documentation under the "Props" section in the readme.md file.

Everything is covered within the readme including typescript, reactivity, abstraction of methods, etc.

Hope this helped! 😊

**Comment by janie-lee-developer** [comment]
Thank you so much @jamesrweb ! 

Can I ask you one more question, please? If I pass a function as a prop to <ReactP5Wrapper myFunc={myFunc} />, how can I call this function inside the sketch.js? 
```
p5.updateWithProps = (props) => {
    props.handleCurrentPose(poseLabel);
  };
```

For my code, it's ml5 inside P5 sketch that's creating a label of a pose, so I am trying to call the myFunc(label) with label value I got from sketch. Now I understand we can pass prop, but now I'm trying to send value to the parent component by calling a function that's passed as a prop. Please advise~ Thank you!

**Comment by jamesrweb** [comment]
You can just pass the function via a prop of your choice like `myHandlerProp={myHandlerFunction}` then use the props passed to the update function to call it like `props.myHandlerProp(arguments)`.

Does that make sense?
