### ISSUE TITLE
Render children on top of canvas

### ISSUE THREAD

**Issue by MarkFuller1** [jamesrweb/react-p5-wrapper#164]
## Expected Behavior
To be able to render react components on top of the canvas

## Actual Behavior
If I use
``` js
const App = () => {
  return (
    <ReactP5Wrapper sketch={sketch}>
      <div>Hello</div>
    </ReactP5Wrapper>
  );
};
```
The canvas is simply rendered after the `<div>`

## Steps to Reproduce the Problem

1. Follow tutorial on readme
2. Add child components

Package Version: `^3.3.0`

**Comment by jamesrweb** [comment]
Can you give me an example of what you're trying to achieve with this? Have you a specific idea in mind?

The elements are added as children of the canvas wrapper and so simple css can be used to do any positioning you require, right?

**Comment by jamesrweb** [comment]
I just noticed in the docs for the children section it doesn't state clearly that to put children "on top" you need to use css. I'll also update that section of the readme and add an example as soon as I can or feel free to make a PR if you'd like to take that on 👌🏻!
