### ISSUE TITLE
createCapture(video:{facingMode:{exact:"user"} .. not working?

### ISSUE THREAD

**Issue by janie-lee-developer** [jamesrweb/react-p5-wrapper#165]
## Expected Behavior
Mobile video and desktop video captures to work.

## Actual Behavior
Mobile video + Desktop video both don't work with below code:
`   video = p5.createCapture({
         audio: false,
         video: {
             facingMode: {
             exact: "user",
           },
         },
       });`

-------------------------
Mobile video don't work, but desktop vid works with below code:
`   video = p5.createCapture(p5.VIDEO);`

## Specifications

Package Version:^3.3.0

**Comment by jamesrweb** [comment]
It works fine for me with both examples you shared but I made an optimised solution for you nevertheless... not sure why you are having issues though, hope this helps.

**Typescript:**

```tsx
import React from "react";
import type { Element as P5Element } from "p5";
import { ReactP5Wrapper, Sketch, P5Instance, SketchProps } from "react-p5-wrapper";

function createCapture(p5: P5Instance<SketchProps>) {
  if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){
    return p5.createCapture({ audio: false, video: { facingMode: { exact: "user" }}});
  }

  return p5.createCapture(p5.VIDEO);
}

const sketch: Sketch = p5 => {
  let capture: P5Element;
  
  p5.setup = () => {
    capture = createCapture(p5);
    capture.hide();
    p5.createCanvas(p5.windowWidth, p5.windowHeight);
  }

  p5.draw = () => {
    p5.image(capture, 0, 0, p5.width, p5.height);
  };
};

export default function App() {
  return <ReactP5Wrapper sketch={sketch} />;
}
```

**Javascript:**

```jsx
import React from "react";
import { ReactP5Wrapper } from "react-p5-wrapper";

function createCapture(p5) {
  if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){
    return p5.createCapture({ audio: false, video: { facingMode: { exact: "user" }}});
  }

  return p5.createCapture(p5.VIDEO);
}

const sketch = p5 => {
  let capture;
  
  p5.setup = () => {
    capture = createCapture(p5);
    capture.hide();
    p5.createCanvas(p5.windowWidth, p5.windowHeight);
  }

  p5.draw = () => {
    p5.image(capture, 0, 0, p5.width, p5.height);
  };
};

export default function App() {
  return <ReactP5Wrapper sketch={sketch} />;
}
```

The `createCapture` function just checks if we are on mobile or tablet and if we are, use the user facing camera. Otherwise just capture normal input from the default video feed on all other cases.

**Comment by jamesrweb** [comment]
Oh and for reference I tested on desktop (macOS + chrome, macOS + safari, windows + chrome) and on my iPhone to validate both examples 😄 .
