### ISSUE TITLE
Sudden issue with vector.mult

### ISSUE THREAD

**Issue by InvisiBug** [jamesrweb/react-p5-wrapper#213]
I've suddenly started seeing the following error when running a sketch that I haven't changed in months
        `p5.Vector.prototype.mult: x, y, or z arguments are either undefined or not a finite number`
I haven't updated any packages since starting my project so I'm not sure whats causing the problem.
I tried checking out a much earlier commit in my project history and still see the same problem

Nextjs version 12.1.6
React wrapper version 3.4.0

Any help would be greatly appreciated

**Comment by InvisiBug** [comment]
Everything has started working again with no code changes. No idea why this happened. It seems to have effect all my sketches that performed Vector operations.

**Comment by jamesrweb** [comment]
Interesting, I'm sure it was some local cache issue or something but if it comes up again, let me know. Everything should be stable with the library up to and including the latest P5 release though.
