### ISSUE TITLE
Problem with updateWithProps deeply comparing object.

### ISSUE THREAD

**Issue by manolara** [jamesrweb/react-p5-wrapper#227]
## Expected Behavior
passing an object prop to `<ReactP5Wrapper>` triggers shallow comparison and re-render occurs only when address reference of object changes

## Actual Behavior
 passing as prop a large object (Tone.js synth) causes huge prop comparison/ re-rendering time (over 2s), makes application unusable. 

## Specifications:
I am using a p5 and Tone.js to create a music related app. Currently working on connecting an 'instrument' component (a p5js interactive sketch that allows users to create a note sequence) to a sound source (a synthesizer component using Tone.js). I want to pass the Tone.js synth object (that is controlled by the synth component) to the 'instrument' component ,so that it can handle triggering the synth according to the note sequence inputted by the user. 

However, when passing a tone.js Polysynth instance as props to `<P5ReactWrapper/>` the deep comparison that occurs causes huge delay times in re-rendering, given that Polysynth is a fairly large Object. This is particularly problematic as in my case I don't care about whether the difference lies within the synth's **parameters** - I only want to it to check for changes in the synth prop's **adress** (i.e. wether the user want's to connect the instrument to a different synth instance.) 

Regular React components handle this case perfectly, but the way `<ReactP5Wrapper>` handles prop updates (src/utils/propsAreEqual.ts) causes many performance issues in my use case. 

Is there a way I could bypass the deep comparison for specific `<ReactP5Wrapper>` instances or maybe would it be possible to implement that possibility with a PR?

Thank you !

Package Version:
4.1.0

**Comment by jamesrweb** [comment]
Can you provide a minimal working code sample (as small as possible) to see what it is you're doing and test what you've reported?

**Comment by jamesrweb** [comment]
Feel free to also make a PR if you already have a suggestion by the way.

**Comment by manolara** [comment]
Yes! Thanks for getting back to me :)

I thought the best way to go about this was to make two little sandboxes: one that replicates the issue occurring with p5Wrapper and one without - to demonstrate the expected behaviour performance-wise.

Demo with p5wrapper:

https://codesandbox.io/s/demo-with-p5wrapper-0miqhy

Demo without p5wrapper:

https://codesandbox.io/s/loving-farrell-xwbi9p?file=/src/Parent.tsx

btw in the demo with the wrapper if this error occurs (doesnt always happen) 
Error: "Start time must be strictly greater than previous start time"
it's because the delay caused by the comparison causes the scheduler to miss the expected start time to trigger note and then behaves oddly.

As I was fiddling with it I realized that a different approach could be to: Avoid passing down the whole synth instance - instead pass the callback function that is used within the Tone.Loop instance which will in itself contain the sound source information. 
Maybe that would work, but I'll have to try it first.

**Comment by manolara** [comment]
Regardless, I'll try to work on PR today because I think it'll be very useful to have an option to bypass the deep comparison, as for some cases it can create issues.

**Comment by manolara** [comment]
Ok so I've gotten it to work locally and i believe its a good solution in terms on it's impact on the api. However it's a bit hacky and would definitely like to see your opinion on that.

Newbie problem though😅  Not too sure how to make a PR on this repo. I've tried pushing to master, pushing a new branch up and also forking and pushing my changes there. Nevertheless, I can't seem to get any of these to work and always get:

`ERROR: Permission to P5-wrapper/react.git denied to manolara.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

Any help would be more than appreciated!

**Comment by jamesrweb** [comment]
So you did [this](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)?

Fork -> Create PR -> target this repo with changes from your repo

Or?

**Comment by manolara** [comment]
Figured it out, PR is now open!

**Comment by jamesrweb** [comment]
Just reviewed #229, see comments for required changes / discussions.

**Comment by jamesrweb** [comment]
Hi @manolara, this branch `synth-test` contains your changes plus the latest `master` branch changes. Some notes:

- It seems that not all controls are visible on all demo sketches
- When the synth sketch is unmounted, an error it thrown
- When the deep compare option is set and the synth version is changed, it hangs for 3-6 seconds, is this expected?

If you could take a look again I would appreciate it but if you can't or won't, just let me know! Thanks in advance for the work so far 😄 🚀

**Comment by jamesrweb** [comment]
Closed due to inactivity.
