### ISSUE TITLE
TypeError: p5.loadSound is not a function

### ISSUE THREAD

**Issue by Tebesski** [jamesrweb/react-p5-wrapper#278]
## Expected Behavior
loadSound function loads sound

## Actual Behavior
TypeError: p5.loadSound is not a function

## Steps to Reproduce the Problem

1. use p5.loadSound function as per the documentation

## Specifications

Package Version:
4.2.0

**Comment by jamesrweb** [comment]
Please read through the project documentation, there's a whole example on how to use external libraries, plugins and constructors such as sound, vector, etc there.

**Comment by CharlesFauman** [comment]
Hello, I've been trying and failing for about two hours to get sound working as well.

As the user here I think was trying to say, the exact code in the documentation on how to use p5.loadSound does not work locally for me, on the latest packages.

I'm using bun + vite + this library - I get `p5.loadSound is not a function` running the example from the readme.

"@p5-wrapper/react": "^4.3.4"
"p5": "^1.9.0"

**Comment by jamesrweb** [comment]
Then you need to show me that that is the case with a sample project, which uses the example exactly as provided, in your setup as a replication and with a build showing it doesn't work for you, because I test all the examples before releasing new package versions and it's fine for me.

**Comment by kazuemon** [comment]
I have encountered a similar problem with Vite + React.
I was able to access the method with `window.p5.prototype.loadSound()`, though in a forced way.
