### ISSUE TITLE
npm ERR! Usage Error: This project is configured to use npm

### ISSUE THREAD

**Issue by larsmosr** [jamesrweb/react-p5-wrapper#299]
## Expected Behavior
Installation of the package
## Actual Behavior
npm ERR! code 1
npm ERR! path /Users/larsfamigo/Devio/Projects/bam-productions/node_modules/@p5-wrapper/react
npm ERR! command failed
npm ERR! command sh -c pnpm format
npm ERR! Usage Error: This project is configured to use npm
npm ERR! 
npm ERR! $ pnpm ...
## Steps to Reproduce the Problem
1. npm install @p5-wrapper/react

## Specifications

Package Version:

**Comment by jamesrweb** [comment]
The post install script is probable being executed by your NPM installation but it shouldn't do that for a sub package... I'll make a new deployment to remove that later today.

**Comment by jamesrweb** [comment]
Deployment of v4.3.2 complete. Please reinstall at the latest version and update this issue accordingly.
