### ISSUE TITLE
Examples directory doesn't exist, link broken on README

### ISSUE THREAD

**Issue by studiosi** [jamesrweb/react-p5-wrapper#320]
## Expected Behavior

Link on Readme that points to the examples actually points to the examples

## Actual Behavior

Link is broken and redirect to a "not found" page

## Steps to Reproduce the Problem

1. Click the link on Readme

## Specifications

Package Version: latest

**Comment by yevdyko** [comment]
Thank you @studiosi for pointing that out. The fix is on the way

**Comment by yevdyko** [comment]
The correct link: https://github.com/P5-wrapper/react/tree/master/demo/sketches

**Comment by yevdyko** [comment]
The fix is ready. Please have a look when you are free @jamesrweb
