### ISSUE TITLE
Module parse failed: Identifier 'XX' has already been declared (7762:41)

### ISSUE THREAD

**Issue by rlisac** [jamesrweb/react-p5-wrapper#324]
Hello everyone

do you have an idea why the following error occurs in my next.js 14 application?

./node_modules/@p5-wrapper/react/dist/component/react.js
Module parse failed: identifier 'je' was already declared (7762:41)
| if (F ? k || ($ = !0, A(), k = !0) : $ = !!je.first, H = Math.max(0, Math.floor(H)), Q = Math.max(0, Math.floor(Q)), $) {
| if (!re) throw new Error("First frame must contain a { palette } option");
> var [je, we, fe, De, he = 8] = [
| G,
| H,

Node 18.18
Next.js 14

I also have the same behavior when I work with https://github.com/P5-wrapper/next

Thanks for a short feedback.

**Comment by daneden** [comment]
Came here to report the same issue with the same setup!

**Comment by jamesrweb** [comment]
Assuming it's the same issue as #314 where NextJS itself is the issue here.

**Comment by rlisac** [comment]
Thank you very much @jamesrweb . That was the solution.
