### ISSUE TITLE
Missing typings for `ReactP5WrapperGuard` in 5.0.0-rc.0

### ISSUE THREAD

**Issue by judehunter** [jamesrweb/react-p5-wrapper#397]
I just installed `@p5-wrapper/react` with pnpm and it seems like the typings for `ReactP5WrapperGuard` can't be found by typescript in the declaration files. This in turn makes `ReactP5Wrapper` untyped. This only happens in 5.0.0-rc.0

## Expected Behavior
The typings for `ReactP5WrapperGuard` are defined.

## Actual Behavior
They aren't :)

## Steps to Reproduce the Problem

1. `pnpm install @p5-wrapper/react`
2. `import { ReactP5Wrapper } from "@p5-wrapper/react";`
3. `<ReactP5Wrapper sketch={} />` - `Type '{ sketch: any; }' is not assignable to type 'IntrinsicAttributes'.`

## Specifications

Package Version: 5.0.0-rc.0

**Comment by jamesrweb** [comment]
As described in the docs:

> Note: Version 5 is still in development, currently 5.0.0-rc.0 has been released for internal development testing ONLY. It is recommended to continue utilising version 4.4.0 until it is out of the rc versioning scheme.

**Comment by jamesrweb** [comment]
I published v4.4.1 as `latest` to avoid others hitting this in future and will re-release v5.0.0-rc.1 as `next` instead.
