### ISSUE TITLE
npm package for version 4.4.1 is empty

### ISSUE THREAD

**Issue by weakit** [jamesrweb/react-p5-wrapper#403]
The package doesn't have the dist folder in it:
https://www.npmjs.com/package/@p5-wrapper/react/v/4.4.1?activeTab=code

4.4.0 is fine.

Maybe push another package?

**Comment by jamesrweb** [comment]
Please test version `4.4.2` which I just deployed now and let me know if the issue is resolved for you.

**Comment by weakit** [comment]
Works as expected.
Thank you so much!

**Comment by jamesrweb** [comment]
No problem, my apologies for the mistake!
