### ISSUE TITLE
drawingContext is not definied

### ISSUE THREAD

**Issue by NaveedGujral** [jamesrweb/react-p5-wrapper#450]
I'm trying to run this example code from p5js's documentation on how to implement a gradient.

function setup() {
  createCanvas(100, 100);

  background('skyblue');

  // Style the circle using a color gradient.
  let myGradient = drawingContext.createRadialGradient(50, 50, 3, 50, 50, 40);
  myGradient.addColorStop(0, 'yellow');
  myGradient.addColorStop(0.6, 'orangered');
  myGradient.addColorStop(1, 'yellow');
  drawingContext.fillStyle = myGradient;
  drawingContext.strokeStyle = 'rgba(0, 0, 0, 0)';

  // Draw the circle.
  circle(50, 50, 40);

  describe('A fiery sun drawn on a light blue background.');
}

This works in their web editor but when i try it with the wrapper in my react project i get the error drawingContext is not defined.

**Comment by jamesrweb** [comment]
Please read the documentation of this library and implement based on the examples provided there. Your issue is that you are trying to use `p5` in _**global mode**_ but this library is only for use in _**instance mode**_.
